### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ramn** [alkis/decimal#22]
The repo says the license is Apache 2.0, but the decNumber library seems to be GPL. Is it really possible to license this library as Apache 2.0?

**Comment by alkis** [comment]
Afaik decNumber is dual licensed as gpl and bsd.

On Dec 14, 2016 12:07, "Simon Andersson" <notifications@github.com> wrote:

The repo says the license is Apache 2.0, but the decNumber library seems to
be GPL. Is it really possible to license this library as Apache 2.0?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alkis/decimal/issues/22>, or mute the thread

**Comment by ramn** [comment]
Thanks @alkis! Do you have a link that supports this claim?

**Comment by ramn** [comment]
Here is something in the header: https://sourceware.org/svn/gcc/tags/stack-last-merge/libdecnumber/decNumber.h

**Comment by ramn** [comment]
The copies in your repo says 'ICU License', where does these files come from?

**Comment by alkis** [comment]
http://speleotrove.com/decimal/decnumber.html

Lists two sources. One from ICU and one from gnu gcc. The licences are ICU
and GPL perspectively.

**Comment by ramn** [comment]
Thanks! So the ICU license is compatible with Apache 2?

**Comment by alkis** [comment]
Yes. Read this:

https://www.apache.org/legal/resolved#category-a

**Comment by ramn** [comment]
Thank you, good link! My question is answered.
